# languages.py

TRANSLATIONS = {
    # --- 中文 ---
    'zh': {
        # === 全局 & 数据库 ===
        "app_title": "个人资产管理系统",
        "db_not_found": "数据库文件未找到，请先运行 init_db.py 初始化数据库！",
        "db_sync_success": "数据已成功同步！",
        "db_save_fail": "保存失败: {}",
        
        # === 登录页 ===
        "login_page_title": "💼 个人资产管理",
        "login_tab_login": "登录",
        "login_tab_reg": "注册",
        "login_username": "用户名",
        "login_password": "密码",
        "login_btn_login": "登录",
        "login_success": "登录成功！",
        "login_error": "账号或密码错误",
        "login_new_user": "新用户名",
        "login_new_pass": "新密码",
        "login_btn_reg": "注册",
        "reg_success": "注册成功，请登录",
        "reg_fail_exist": "用户名已存在",

        # === 资产与标签管理 ===
        "assets_header": "资产与标签管理",
        "filter_expander": "🔍 高级筛选 (支持查找未分类资产)",
        "filter_kw": "1. 关键字搜索",
        "filter_kw_ph": "资产名或代码...",
        "filter_group": "2. 选择标签组",
        "filter_no_filter": "(不筛选)",
        "filter_tag_state": "3. 筛选 '{}' 下的状态",
        "filter_tag_none": "【无此标签】",
        "filter_tag_ph": "留空则显示全部",
        "tab_assets": "1. 资产列表",
        "tab_tags": "2. 标签定义",
        "tab_batch": "3. 关联打标",
        "assets_caption_count": "共显示 {} 条资产",
        "col_id": "ID",
        "col_name": "资产名称",
        "col_code": "代码",
        "col_type": "大类",
        "col_remarks": "备注",
        "col_remarks_help": "例如：养老金、准备卖出...",
        # 资产类型 (建议只用于显示，存库建议存 Code)
        "type_fund": "基金",
        "type_stock": "股票",
        "type_bond": "债券",
        "type_cash": "现金",
        "type_other": "其他",
        "btn_save_asset": "💾 保存资产变动",
        "col_tag_group": "标签组",
        "col_tag_name": "标签名",
        "btn_save_tag": "💾 保存标签变动",
        "batch_header": "### 🏷️ 批量资产打标",
        "col_current_tags": "当前标签",
        "batch_caption_count": "当前筛选结果: {} 个资产",
        "batch_btn_sel_all": "✅ 全选当前",
        "batch_help_sel_all": "选中当前列表中的所有资产",
        "batch_btn_sel_none": "⬜ 取消全选",
        "batch_help_sel_none": "取消所有勾选",
        "batch_action_label": "##### 🛠️ 批量操作",
        "batch_warn_no_tags": "暂无标签，请先去【标签定义】页签添加。",
        "batch_filter_group": "1. 先筛选标签组",
        "batch_filter_group_ph": "留空则显示全部标签...",
        "batch_select_tags": "2. 选择要应用的标签 (可选 {} 个)",
        "batch_select_tags_ph": "可多选...",
        "batch_action_mode": "3. 操作模式",
        "mode_add": "➕ 添加 (保留已有)",
        "mode_cover": "🔄 覆盖 (清除旧标)",
        "mode_remove": "➖ 移除 (仅删选中)",
        "batch_btn_update": "🚀 执行更新",
        "batch_warn_sel_asset": "请在表格左侧勾选至少一个资产！",
        "batch_warn_sel_tag": "请选择要操作的标签！",
        "batch_success_update": "✅ 成功更新 {} 个资产！",

        # === 数据录入 ===
        "entry_header": "📝 每日资产快照录入",
        "entry_date_label": "选择快照日期",
        "entry_warn_no_asset": "暂无资产。",
        "entry_expander_filter": "🔍 筛选与排序工具",
        "entry_kw_label": "关键字搜索",
        "entry_kw_ph": "名称/代码",
        "entry_group_label": "标签组",
        "entry_tag_label": "标签名",
        "entry_sort_caption": "设置列表排序方式：",
        "entry_sort_label": "排序依据",
        "sort_default": "默认 (ID)",
        "sort_amt_desc": "💰 总金额 (高→低)",
        "sort_amt_asc": "💰 总金额 (低→高)",
        "sort_profit_desc": "📈 持有收益 (高→低)",
        "sort_profit_asc": "📉 持有收益 (低→高)",
        "sort_yield_desc": "🚀 收益率 (高→低)",
        "sort_yield_asc": "🥀 收益率 (低→高)",
        "entry_info_no_match": "没有符合条件的资产。",
        "entry_caption_show": "当前显示: {} 条",
        "entry_col_amt": "💰 总市值",
        "entry_col_profit": "📈 持有收益",
        "entry_col_cost": "本金",
        "entry_col_yield": "收益率",
        "entry_btn_save": "💾 保存当前数据",
        "entry_success_save": "已保存 {} 条记录！",

        # === 看板 (Dashboard) ===
        "dash_header": "📊 深度资产透视",
        "dash_no_data": "👋 暂无数据，请先前往【数据录入】页面添加资产快照。",
        "dash_date_range": "数据统计范围：{} ~ {}",
        "dash_tab_trend": "📈 趋势分析",
        "dash_tab_daily": "🍰 每日透视",
        "dash_tab_check": "⚠️ 数据校验",
        "trend_title_total": "💰 总资产净值走势",
        "trend_legend_total": "总资产",
        "trend_legend_profit": "持有收益",
        "trend_legend_yield": "收益率",
        "trend_y_amt": "金额 (万)",
        "trend_y_yield": "收益率 (%)",
        "trend_btn_export_csv": "📥 导出总资产趋势数据 (CSV)",
        "trend_help_export": "包含每日的总资产、总收益、总本金和综合收益率",
        "trend_struct_title": "📊 结构化趋势详细对比",
        "trend_view_mode": "分析维度",
        "view_by_asset": "按具体资产",
        "view_by_tag": "按标签组",
        "trend_metric_label": "画图指标 (Y轴)",
        "metric_amt": "总金额 (Amount)",
        "metric_profit": "持有收益 (Profit)",
        "metric_yield": "收益率 (Yield %)",
        "metric_share": "占比 (Share %)",
        "trend_tooltip_label": "🖱️ 悬停显示额外指标",
        "tt_amt": "总金额",
        "tt_profit": "持有收益",
        "tt_cost": "本金",
        "tt_yield": "收益率",
        "tt_share": "占比",
        "trend_warn_no_tags": "暂无标签数据。",
        "trend_sel_group": "选择标签分组",
        "trend_btn_export_struct": "📥 导出当前筛选数据 ({})",
        "daily_subheader": "🍰 每日资产快照分析",
        "daily_sel_date": "📅 选择要查看的日期",
        "daily_sel_dim": "🔍 分析维度 (筛选标签组)",
        "daily_metric_total": "当日总资产",
        "daily_metric_profit": "当日持有收益",
        "daily_metric_yield": "当日综合收益率",
        "daily_pie_amt_title": "【总金额】占比 ({})",
        "daily_warn_neg_profit": "⚠️ 注意：饼图仅展示盈利部分。",
        "daily_pie_pos_prof_title": "【正收益】贡献占比 ({})",
        "daily_pie_prof_title": "【持有收益】占比 ({})",
        "daily_table_title": "📋 详细数据表",
        "daily_col_name_tag": "名称/标签",
        "daily_btn_export": "📥 导出当日数据表 ({})",
        "daily_info_no_data": "该日期/维度下无数据。",
        "check_warn_missing": "发现 {} 条聚合记录数据缺失！",
        "check_success": "🎉 数据完整。",
        "check_no_tags": "暂无标签数据。",

        # === 定投计划 ===
        "plans_header": "📅 定投计划与未来现金流",
        "plans_tab_manage": "⚙️ 计划管理",
        "plans_tab_cashflow": "🔮 未来现金流看板",
        "plans_caption": "在这里管理你的自动定投计划（仅用于统计未来资金需求，不会自动记账）。",
        "plans_expander_new": "➕ 新增定投计划",
        "plans_warn_no_assets": "⚠️ 请先去【资产与标签管理】页面添加至少一个资产。",
        "plans_step1": "##### 🔍 第一步：筛选资产",
        "plans_filter_tag_state": "标签状态",
        "plans_step2": "##### 📝 第二步：设置定投参数",
        "plans_info_no_match": "没有符合筛选条件的资产。",
        "plans_sel_asset": "选择资产 (当前筛选出 {} 个)",
        "plans_input_amt": "每次定投金额",
        "plans_input_freq": "频率",
        "plans_freq_week": "每周",
        "plans_freq_month": "每月",
        "plans_freq_day": "每天",
        "plans_sel_weekday": "选择周几",
        "plans_sel_monthday": "选择每月几号 (建议1-28日)",
        "plans_btn_save": "💾 保存定投计划",
        "plans_error_amt": "定投金额必须大于 0",
        "plans_success_add": "✅ 已添加对【{}】的定投计划！",
        "plans_list_header": "📋 正在运行的计划",
        "plans_col_desc": "定投时间",
        "plans_col_active": "启用中",
        "plans_btn_save_changes": "💾 保存计划变更",
        "plans_info_no_plans": "暂无定投计划。",
        "plans_cf_subheader": "🗓️ 未来 30 天资金需求推演",
        "plans_info_enable_first": "请先启用至少一个定投计划。",
        "plans_warn_no_days": "未来30天内没有匹配的定投日。",
        "plans_metric_total_30d": "未来 30 天总定投金额",
        "plans_metric_daily_avg": "平均每日资金流出",
        "plans_dim_stack": "选择分析维度 (堆叠方式)",
        "plans_chart_title": "未来 30 天每日定投分布 ({})",
        "plans_chart_y": "金额",
        "plans_chart_x": "日期",
        "plans_chart_cat": "类别",
        "plans_expander_cal": "查看详细扣款日历",
        "plans_col_date": "日期",
        "plans_col_asset": "扣款资产",
        "plans_col_amt": "扣款金额",
        "weekday_mon": "周一",
        "weekday_tue": "周二",
        "weekday_wed": "周三",
        "weekday_thu": "周四",
        "weekday_fri": "周五",
        "weekday_sat": "周六",
        "weekday_sun": "周日",

        # === 投资笔记 ===
        "notes_header": "📒 投资笔记与复盘",
        "notes_caption": "记录每一次决策的思考，构建自己的投资体系。",
        "notes_expander_new": "✍️ 写一篇新笔记",
        "notes_input_title": "标题",
        "notes_ph_title": "例如：美股大跌，加仓机会？",
        "notes_input_content": "正文",
        "notes_ph_content": "记录你的分析、情绪和操作计划...",
        "notes_btn_publish": "🚀 发布笔记",
        "notes_warn_empty_title": "标题不能为空",
        "notes_success_publish": "发布成功！",
        "notes_timeline": "⏳ 笔记时间轴",
        "notes_info_empty": "还没有笔记，快去写第一篇吧！",
        "notes_edit_label": "##### 📝 编辑中...",
        "notes_btn_save": "💾 保存",
        "notes_btn_cancel": "❌ 取消",
        "notes_caption_updated": "📝 修改于: {}",
        "notes_btn_edit": "✏️ 编辑",
        "notes_btn_del": "🗑️ 删除",
        "notes_success_del": "已删除",

        # === FIRE 推演 ===
        "fire_header": "🔥 FIRE 财富自由展望",
        "fire_caption": "推演未来 50 年的资产复利增长，看看你在多少岁能实现财务自由。",
        "fire_input_total": "当前总资产 (万元)",
        "fire_input_age": "当前年龄 (岁)",
        "fire_input_rate": "预期年化收益率 (%)",
        "fire_input_add": "每年追加本金 (万元)",
        "fire_help_add": "假设每年工资结余用于投资的金额",
        "fire_chart_title": "未来 50 年资产增长趋势 (单位: 万)",
        "fire_chart_x": "年份",
        "fire_chart_y": "金额 (万)",
        "fire_legend_total": "总资产 (复利)",
        "fire_legend_profit": "累计复利收益",
        "fire_legend_principal": "投入本金",
        "fire_marker_text": "🚩 {}岁: 破 {} 万",
        "fire_script_title": "### 💡 人生财富剧本",
        "fire_script_intro": "假设你从 **{}岁** 开始，现有 **{:.2f}万**，保持 **{}%** 的年化收益，每年坚持定投 **{:.1f}万**：",
        "fire_script_point": "* **{}岁 ({}年)**：资产达到 **{:.0f}万**（本金 {:.0f}万 + 收益 {:.0f}万）。",
        "fire_script_magic": "🚀 **神奇时刻**：在 **{}岁 ({}年)**，你的累计复利收益（{:.0f}万）将首次超过你的累计投入本金！从这一天起，钱为你打工的效率超过了你为钱打工。",
        "fire_expander_details": "查看详细年份数据",
        "fire_col_year": "年份",
        "fire_col_age": "年龄",
        "fire_col_balance": "预估总资产",
        "fire_col_principal": "累计本金",
        "fire_col_profit": "累计收益",

        # === 设置与备份 ===
        "backup_email_subject": "【自动备份】资产数据备份 - {}",
        "backup_email_body": "这是您的个人资产管理系统数据库自动备份，请妥善保管。\n\n备份时间: {}",
        "backup_log_local": "本地备份已保存: {}",
        "backup_status_no_conf": "未配置邮件",
        "backup_status_sent": "邮件已发送",
        "backup_status_fail": "邮件失败: {}",
        "backup_toast_start": "正在后台执行自动备份...",
        "backup_toast_success": "自动备份完成！\n{}",
        "backup_error": "自动备份失败: {}",
        "settings_header": "⚙️ 系统设置与备份",
        "settings_tab_policy": "🔄 备份策略与邮箱",
        "settings_tab_local": "📂 本地备份管理 & 恢复",
        "settings_sub_policy": "1. 自动备份策略",
        "settings_cap_policy": "系统将在你打开应用时，根据上次备份时间自动判断是否需要执行备份。",
        "settings_label_freq": "备份频率",
        "settings_freq_off": "关闭",
        "settings_freq_day": "每天",
        "settings_freq_week": "每周",
        "settings_freq_month": "每月",
        "settings_sub_email": "2. 邮箱推送设置 (推荐)",
        "settings_cap_email": "配置 SMTP 后，每次备份都会将数据库文件发送到你的邮箱。这是防止 SD 卡损坏的最佳保障。",
        "settings_ph_host": "例如 smtp.qq.com",
        "settings_label_port": "SMTP 端口",
        "settings_ph_user": "你的邮箱@qq.com",
        "settings_label_pass": "授权码/密码",
        "settings_help_pass": "注意：QQ邮箱请使用授权码",
        "settings_label_to": "接收邮箱 (留空则发给自己)",
        "settings_btn_save": "💾 保存配置",
        "settings_success_save": "配置已保存！",
        "settings_btn_test": "📧 发送测试邮件",
        "settings_spinner_test": "正在发送...",
        "settings_success_test": "测试成功！{}",
        "settings_sub_local": "📂 本地备份文件管理",
        "settings_btn_manual": "🚀 立即手动备份",
        "settings_spinner_backup": "正在备份中...",
        "settings_info_no_files": "暂无本地备份文件。",
        "settings_col_filename": "文件名",
        "settings_col_time": "备份时间",
        "settings_col_size": "大小 (KB)",
        "settings_label_action": "🛠️ 操作特定备份",
        "settings_sel_file": "选择备份文件",
        "settings_btn_download": "📥 下载此备份",
        "settings_btn_restore": "⏪ 从此备份恢复数据",
        "settings_success_restore": "恢复成功！请刷新页面。",
        "settings_error_restore": "恢复失败: {}",
        "settings_btn_del": "🗑️ 删除此备份",
        "settings_sub_import": "📥 外部数据导入 (迁移)",
        "settings_label_upload": "上传 .db 数据库文件 (将覆盖当前所有数据)",
        "settings_btn_import": "⚠️ 确认覆盖并导入",
        "settings_success_import": "导入成功！系统已重置为上传的数据。",

        # === 侧边栏 ===
        "sidebar_lang_login": "选择语言 / Language",
        "sidebar_lang_main": "🌐 Language / 言語",
        "sidebar_welcome": "欢迎回来, {}",
        "sidebar_nav": "导航菜单",
        "nav_dashboard": "📊 资产看板",
        "nav_notes": "📒 投资笔记",
        "nav_assets": "🏦 资产管理",
        "nav_entry": "📝 数据录入",
        "nav_plans": "📅 定投计划",
        "nav_fire": "🔥 FIRE推演",
        "nav_settings": "⚙️ 系统设置",
        "btn_logout": "🚪 退出登录",
    },
    # --- English ---
    "en": {
        "app_title": "💼 Personal Asset Manager",
        "login_title": "💼 Asset Manager",
        "tab_login": "Login",
        "tab_register": "Register",
        "username": "Username",
        "password": "Password",
        "btn_login": "Login",
        "btn_register": "Register",
        "login_success": "Login Successful!",
        "login_fail": "Invalid username or password",
        "sidebar_welcome": "👤 {}",
        "sidebar_nav": "Navigation",
        "nav_dashboard": "Dashboard",
        "nav_notes": "Investment Notes",
        "nav_assets": "Assets & Tags",
        "nav_entry": "Data Entry",
        "nav_plans": "Investment Plans",
        "nav_fire": "🔥 FIRE Projection",
        "nav_settings": "⚙️ Settings & Backup",
        "btn_logout": "Logout",
    },
    # --- 日本語 ---
    "ja": {
        "app_title": "💼 個人資産管理システム",
        "login_title": "💼 資産管理",
        "tab_login": "ログイン",
        "tab_register": "登録",
        "username": "ユーザー名",
        "password": "パスワード",
        "btn_login": "ログイン",
        "btn_register": "登録",
        "login_success": "ログイン成功！",
        "login_fail": "ユーザー名またはパスワードが違います",
        "sidebar_welcome": "👤 {}",
        "sidebar_nav": "ナビゲーション",
        "nav_dashboard": "詳細分析",
        "nav_notes": "投資ノート",
        "nav_assets": "資産とタグ管理",
        "nav_entry": "データ入力",
        "nav_plans": "積立プラン",
        "nav_fire": "🔥 FIRE 展望",
        "nav_settings": "⚙️ 設定とバックアップ",
        "btn_logout": "ログアウト",
    }
}